### ISSUE TITLE
Missing Declaration File for Module

### ISSUE THREAD

**Issue by GitariDev** [njwest/react-native-weather#3]
I'm having trouble with using the component due to a missing declaration file for the Module. This is prohibiting me from importing the weather widget from 'react-native-weather'. Any possible solutions? Thanks.

**Comment by njwest** [comment]
@OG3than Are you importing the module as `import { WeatherWidget } from 'react-native-weather';` with `WeatherWidget` in curly braces( **{ }** )? 

If you are using curly braces in your import statement and you still get a missing declaration error, can you copy & paste your code and the full error message in a comment on this issue?

**Comment by GitariDev** [comment]
Yes. I am. Let me do that.

**Comment by njwest** [comment]
I am going to assume that adding curly braces fixed the issue because I am unable to reproduce it -- please comment with the code that gives you this error and the full error message if you are still having trouble with this and I'll re-open the issue
